"""add fingerprint reference to key_logs

Revision ID: 30643b568a48
Revises: 
Create Date: 2026-01-16 14:15:53.713657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30643b568a48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_fp_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_in_fp_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_out_fp_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_logs', schema=None) as batch_op:
        batch_op.drop_column('staff_out_fp_id')
        batch_op.drop_column('staff_in_fp_id')
        batch_op.drop_column('borrower_fp_id')

    # ### end Alembic commands ###
